const data = [
  {
    Name: 'Mobile',
    Cycle: 'Monthly',
    Price: 100,
    VideoQuality: 'Good',
    Resolution: '480p',
    Devices: ['Phone'],
    NumberOf: 1,
  },
  {
    Name: 'Basic',
    Cycle: 'Monthly',
    Price: 200,
    VideoQuality: 'Good',
    Resolution: '720p',
    Devices: ['Phone', 'Tablet'],
    NumberOf: 3,
  },
  {
    Name: 'Standard',
    Cycle: 'Monthly',
    Price: 500,
    VideoQuality: 'Good',
    Resolution: '1080p',
    Devices: ['Phone', 'Tablet', 'Computer'],
    NumberOf: 5,
  },
  {
    Name: 'Premium',
    Cycle: 'Monthly',
    Price: 700,
    VideoQuality: 'Best',
    Resolution: '4K+HDR',
    Devices: ['Phone', 'Tablet', 'Computer', 'TV'],
    NumberOf: 10,
  },
  {
    Name: 'Mobile',
    Cycle: 'Yearly',
    Price: 1000,
    VideoQuality: 'Good',
    Resolution: '480p',
    Devices: ['Phone'],
    NumberOf: 1,
  },
  {
    Name: 'Basic',
    Cycle: 'Yearly',
    Price: 2000,
    VideoQuality: 'Good',
    Resolution: '720p',
    Devices: ['Phone', 'Tablet'],
    NumberOf: 3,
  },
  {
    Name: 'Standard',
    Cycle: 'Yearly',
    Price: 5000,
    VideoQuality: 'Good',
    Resolution: '1080p',
    Devices: ['Phone', 'Tablet', 'Computer'],
    NumberOf: 5,
  },
  {
    Name: 'Premium',
    Cycle: 'Yearly',
    Price: 7000,
    VideoQuality: 'Best',
    Resolution: '4K+HDR',
    Devices: ['Phone', 'Tablet', 'Computer', 'TV'],
    NumberOf: 10,
  },
];

const userInfo = [
  {
    Name: 'Aryan Kodinya',
    Email: 'aryan.kodinya@gmail.com',
    Password: 'Aryankd9@',
    PlanStatus: 'Active',
    PlanCycle: 'Yearly',
    PlanName: 'Basic',
    Price: 2000,
    VideoQuality: 'Good',
    Resolution: '720p',
    Devices: ['Phone', 'Tablet'],
    NumberOf: 3,
    Date: new Date(),
  },
  {
    Name: 'Aryan Sharma',
    Email: 'aryan.kodinya123@gmail.com',
    Password: '123',
    PlanStatus: 'Cancelled',
    PlanCycle: 'Yearly',
    PlanName: 'Basic',
    Price: 2000,
    VideoQuality: 'Good',
    Resolution: '720p',
    Devices: ['Phone', 'Tablet'],
    NumberOf: 3,
    Date: new Date(),
  },
];
export { data, userInfo };
